import net.dongliu.requests.Requests;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.yawlfoundation.cluster.scheduleModule.entity.Engine;
import org.yawlfoundation.cluster.scheduleModule.repo.EngineRepo;
import org.yawlfoundation.cluster.scheduleModule.service.ConnectionService;
import org.yawlfoundation.yawl.engine.interfce.interfaceA.InterfaceA_EnvironmentBasedClient;
import org.yawlfoundation.yawl.util.StringUtil;

import java.io.IOException;
import java.nio.charset.Charset;
import java.util.HashMap;

/**
 * Created by fantasy on 2016/6/20.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:applicationContext.xml")
public class yawlClientTest {
	@Autowired
	private EngineRepo engineRepo;

	@Autowired
	private ConnectionService connectionService;
    @Test
    public void Test() {
		String a = "<response><yawlService id=\"http://localhost:8080/yawlWSInvoker\"><documentation>web service invoker</documentation><servicename>wsInvokerService</servicename><servicepassword>8phRh2xst/DA3WrZHhuyU4Hzle8=</servicepassword><assignable>true</assignable></yawlService><yawlService id=\"http://localhost:8080/workletService/ib\"><documentation>the worklet service</documentation><servicename>workletService</servicename><servicepassword>UMmCkMt6LZo2d0/aThXvTWrTiKA=</servicepassword><assignable>true</assignable></yawlService><yawlService id=\"http://localhost:8000/scheduleModule/routing/5767b5afb20dd21d98abbaef/resourceService/127.0.0.1/2000/ib\"><documentation></documentation><servicename>DefaultWorklist</servicename><servicepassword>ehBHOJc1c7Y/E73HodgW4JtgFq0=</servicepassword><assignable>false</assignable></yawlService><yawlService id=\"http://localhost:8080/mailService/ib\"><documentation>mail service</documentation><servicename>mailService</servicename><servicepassword>iH2HgTZHFwlTk3SFQVQNZykH13g=</servicepassword><assignable>true</assignable></yawlService></response>";
        String b = "";
        System.out.println(StringUtil.unwrap(a));
//        Document doc = null;
//        try {
//            doc = DocumentHelper.parseText(a);
//        } catch (DocumentException e) {
//            e.printStackTrace();
//        }
//        Element res = DocumentHelper.createElement("response");
//        for (Object e : doc.getRootElement().elements()) {
//            res.add(((Element) e).createCopy());
//        }
//        Document newDoc = DocumentHelper.createDocument(res);
//        System.out.println(newDoc.asXML());
    }

    @Test
    public void Tests2() {
		String sp = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
				+ "<specificationSet xmlns=\"http://www.yawlfoundation.org/yawlschema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
				+ "                  version=\"2.2\"\n"
				+ "                  xsi:schemaLocation=\"http://www.yawlfoundation.org/yawlschema http://www.yawlfoundation.org/yawlschema/YAWL_Schema2.2.xsd\">\n"
				+ "    <specification uri=\"hw\">\n" + "        <metaData>\n"
				+ "            <title>import trade procedure</title>\n" + "            <creator>FanTasY</creator>\n"
				+ "            <description>in china</description>\n" + "            <version>0.5</version>\n"
				+ "            <persistent>false</persistent>\n"
				+ "            <identifier>UID_8c36d244-2282-4063-a13c-ef04dd36f5d8</identifier>\n"
				+ "        </metaData>\n" + "        <xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
				+ "            <xs:simpleType name=\"insurance_status\">\n"
				+ "                <xs:restriction base=\"xs:string\">\n"
				+ "                    <xs:enumeration value=\"insured\"/>\n"
				+ "                    <xs:enumeration value=\"urging\"/>\n"
				+ "                    <xs:enumeration value=\"cancel\"/>\n" + "                </xs:restriction>\n"
				+ "            </xs:simpleType>\n" + "            <xs:simpleType name=\"bg_order_status\">\n"
				+ "                <xs:restriction base=\"xs:string\">\n"
				+ "                    <xs:enumeration value=\"not_check\"/>\n"
				+ "                    <xs:enumeration value=\"consistent\"/>\n"
				+ "                    <xs:enumeration value=\"inconsistent\"/>\n"
				+ "                    <xs:enumeration value=\"reject_all\"/>\n" + "                </xs:restriction>\n"
				+ "            </xs:simpleType>\n" + "        </xs:schema>\n"
				+ "        <decomposition id=\"main\" isRootNet=\"true\" xsi:type=\"NetFactsType\">\n"
				+ "            <localVariable>\n" + "                <index>2</index>\n"
				+ "                <name>application_form</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue/>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>3</index>\n"
				+ "                <name>bg</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue/>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>6</index>\n"
				+ "                <name>bg_consistence</name>\n" + "                <type>bg_order_status</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue>not_check</initialValue>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>1</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue/>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>4</index>\n"
				+ "                <name>is_insuranced</name>\n" + "                <type>insurance_status</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue>insured</initialValue>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>0</index>\n"
				+ "                <name>need_insurance</name>\n" + "                <type>boolean</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue/>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>5</index>\n"
				+ "                <name>rejectPlan</name>\n" + "                <type>boolean</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue>true</initialValue>\n" + "            </localVariable>\n"
				+ "            <processControlElements>\n"
				+ "                <inputCondition id=\"InputCondition_1\">\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"sign_contract\"/>\n"
				+ "                    </flowsInto>\n" + "                </inputCondition>\n"
				+ "                <task id=\"sign_contract\">\n" + "                    <name>sign_contract</name>\n"
				+ "                    <flowsInto>\n" + "                        <nextElementRef id=\"apply_bg\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <completedMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/sign_contract/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                        <mapping>\n" + "                            <expression\n"
				+ "                                    query=\"&lt;need_insurance&gt;{/sign_contract/need_insurance/text()}&lt;/need_insurance&gt;\"/>\n"
				+ "                            <mapsTo>need_insurance</mapsTo>\n"
				+ "                        </mapping>\n" + "                    </completedMappings>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-32cabff9-1d7e-47b5-9dd2-74322128ee35</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                        <privileges>\n"
				+ "                            <privilege>\n"
				+ "                                <name>canSuspend</name>\n"
				+ "                                <allowall>true</allowall>\n"
				+ "                            </privilege>\n" + "                            <privilege>\n"
				+ "                                <name>canDeallocate</name>\n"
				+ "                                <allowall>true</allowall>\n"
				+ "                            </privilege>\n" + "                        </privileges>\n"
				+ "                    </resourcing>\n" + "                    <decomposesTo id=\"sign_contract\"/>\n"
				+ "                </task>\n" + "                <task id=\"apply_bg\">\n"
				+ "                    <name>fill_in_bg_form</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"apply_bg_1\"/>\n" + "                    </flowsInto>\n"
				+ "                    <join code=\"xor\"/>\n" + "                    <split code=\"and\"/>\n"
				+ "                    <startingMappings>\n" + "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/main/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <completedMappings>\n"
				+ "                        <mapping>\n" + "                            <expression\n"
				+ "                                    query=\"&lt;application_form&gt;{/fill_in_bg_form/application_form/text()}&lt;/application_form&gt;\"/>\n"
				+ "                            <mapsTo>application_form</mapsTo>\n"
				+ "                        </mapping>\n" + "                    </completedMappings>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-be598bca-7af5-4bad-b645-a83a99863056</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"fill_in_bg_form\"/>\n" + "                </task>\n"
				+ "                <task id=\"apply_bg_1\">\n" + "                    <name>apply_bg</name>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"wait_for_ship_order\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n" + "                            <expression\n"
				+ "                                    query=\"&lt;application_form&gt;{/main/application_form/text()}&lt;/application_form&gt;\"/>\n"
				+ "                            <mapsTo>application_form</mapsTo>\n"
				+ "                        </mapping>\n" + "                    </startingMappings>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-be598bca-7af5-4bad-b645-a83a99863056</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                            <familiarParticipant taskID=\"apply_bg\"/>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"apply_bg\"/>\n" + "                </task>\n"
				+ "                <task id=\"wait_for_ship_order\">\n"
				+ "                    <name>wait_for_ship_order</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"insure\"/>\n"
				+ "                        <predicate ordering=\"0\">boolean(/main/need_insurance/text())!=false</predicate>\n"
				+ "                    </flowsInto>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"check_insurance_doc\"/>\n"
				+ "                        <isDefaultFlow/>\n" + "                    </flowsInto>\n"
				+ "                    <join code=\"xor\"/>\n" + "                    <split code=\"xor\"/>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-d0725c36-ccf5-4e4c-9218-63be84fc1faf</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"wait_for_ship_order\"/>\n" + "                </task>\n"
				+ "                <task id=\"check_insurance_doc\">\n"
				+ "                    <name>check_insurance_doc</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"insured\"/>\n"
				+ "                        <isDefaultFlow/>\n" + "                    </flowsInto>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"urge_for_insurance\"/>\n"
				+ "                        <predicate ordering=\"0\">/main/is_insuranced/text() = 'urging'</predicate>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"xor\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/main/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <completedMappings>\n"
				+ "                        <mapping>\n" + "                            <expression\n"
				+ "                                    query=\"&lt;is_insuranced&gt;{/check_insurance_doc/isInsuranced/text()}&lt;/is_insuranced&gt;\"/>\n"
				+ "                            <mapsTo>is_insuranced</mapsTo>\n"
				+ "                        </mapping>\n" + "                    </completedMappings>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-d0725c36-ccf5-4e4c-9218-63be84fc1faf</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"check_insurance_doc\"/>\n" + "                </task>\n"
				+ "                <task id=\"insure\">\n" + "                    <name>insure</name>\n"
				+ "                    <flowsInto>\n" + "                        <nextElementRef id=\"insured\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/main/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-d0725c36-ccf5-4e4c-9218-63be84fc1faf</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"insure\"/>\n" + "                </task>\n"
				+ "                <condition id=\"insured\">\n" + "                    <name>insured</name>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"order_bg_not_consistent\"/>\n"
				+ "                    </flowsInto>\n" + "                </condition>\n"
				+ "                <task id=\"urge_for_insurance\">\n"
				+ "                    <name>urge_for_insurance</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"insured\"/>\n" + "                    </flowsInto>\n"
				+ "                    <join code=\"xor\"/>\n" + "                    <split code=\"and\"/>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-d0725c36-ccf5-4e4c-9218-63be84fc1faf</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"urge_for_insurance\"/>\n" + "                </task>\n"
				+ "                <task id=\"order_bg_not_consistent\">\n"
				+ "                    <name>order_bg_inconsistent</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"reject\"/>\n"
				+ "                        <predicate ordering=\"0\">/main/bg_consistence/text()='reject_all'</predicate>\n"
				+ "                    </flowsInto>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"goods_arrival\"/>\n"
				+ "                        <isDefaultFlow/>\n" + "                    </flowsInto>\n"
				+ "                    <join code=\"xor\"/>\n" + "                    <split code=\"xor\"/>\n"
				+ "                    <completedMappings>\n" + "                        <mapping>\n"
				+ "                            <expression\n"
				+ "                                    query=\"&lt;bg_consistence&gt;{/order_bg_inconsistent/bg_status/text()}&lt;/bg_consistence&gt;\"/>\n"
				+ "                            <mapsTo>bg_consistence</mapsTo>\n"
				+ "                        </mapping>\n" + "                    </completedMappings>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-d0725c36-ccf5-4e4c-9218-63be84fc1faf</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"order_bg_inconsistent\"/>\n" + "                </task>\n"
				+ "                <task id=\"reject\">\n" + "                    <name>reject</name>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"OutputCondition_1\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n"
				+ "                    <removesTokens id=\"deliver_to_storage\"/>\n"
				+ "                    <removesTokens id=\"goods_arrival\"/>\n"
				+ "                    <removesTokens id=\"inspectation\"/>\n"
				+ "                    <removesTokens id=\"order_bg_not_consistent\"/>\n"
				+ "                    <removesTokens id=\"payment\"/>\n"
				+ "                    <removesTokens id=\"tax\"/>\n" + "                    <removesTokensFromFlow>\n"
				+ "                        <flowSource id=\"tax\"/>\n"
				+ "                        <flowDestination id=\"deliver_to_storage\"/>\n"
				+ "                    </removesTokensFromFlow>\n" + "                    <removesTokensFromFlow>\n"
				+ "                        <flowSource id=\"payment\"/>\n"
				+ "                        <flowDestination id=\"tax\"/>\n"
				+ "                    </removesTokensFromFlow>\n" + "                    <removesTokensFromFlow>\n"
				+ "                        <flowSource id=\"inspectation\"/>\n"
				+ "                        <flowDestination id=\"tax\"/>\n"
				+ "                    </removesTokensFromFlow>\n" + "                    <removesTokensFromFlow>\n"
				+ "                        <flowSource id=\"goods_arrival\"/>\n"
				+ "                        <flowDestination id=\"payment\"/>\n"
				+ "                    </removesTokensFromFlow>\n" + "                    <removesTokensFromFlow>\n"
				+ "                        <flowSource id=\"goods_arrival\"/>\n"
				+ "                        <flowDestination id=\"inspectation\"/>\n"
				+ "                    </removesTokensFromFlow>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet/>\n"
				+ "                            </distributionSet>\n" + "                        </offer>\n"
				+ "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"reject\"/>\n" + "                </task>\n"
				+ "                <task id=\"goods_arrival\">\n" + "                    <name>goods_arrival</name>\n"
				+ "                    <flowsInto>\n" + "                        <nextElementRef id=\"payment\"/>\n"
				+ "                        <predicate>/main/bg_consistence/text()='inconsistent'</predicate>\n"
				+ "                    </flowsInto>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"inspectation\"/>\n"
				+ "                        <predicate>true()</predicate>\n"
				+ "                        <isDefaultFlow/>\n" + "                    </flowsInto>\n"
				+ "                    <join code=\"xor\"/>\n" + "                    <split code=\"or\"/>\n"
				+ "                    <resourcing>\n" + "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-2b008743-5786-40d8-acd9-2859f7a8b1cb</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"goods_arrival\"/>\n" + "                </task>\n"
				+ "                <task id=\"inspectation\">\n" + "                    <name>inspectation</name>\n"
				+ "                    <flowsInto>\n" + "                        <nextElementRef id=\"tax\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-d0725c36-ccf5-4e4c-9218-63be84fc1faf</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"inspectation\"/>\n" + "                </task>\n"
				+ "                <task id=\"payment\">\n" + "                    <name>payment</name>\n"
				+ "                    <flowsInto>\n" + "                        <nextElementRef id=\"tax\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/main/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <decomposesTo id=\"payment\"/>\n"
				+ "                </task>\n" + "                <task id=\"tax\">\n"
				+ "                    <name>tax</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"deliver_to_storage\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"or\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-967f6f96-e4fe-43b0-ae58-ab285b96ae66</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"tax\"/>\n" + "                </task>\n"
				+ "                <task id=\"deliver_to_storage\">\n"
				+ "                    <name>deliver_to_storage</name>\n" + "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"OutputCondition_1\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-2b008743-5786-40d8-acd9-2859f7a8b1cb</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"deliver_to_storage\"/>\n" + "                </task>\n"
				+ "                <outputCondition id=\"OutputCondition_1\"/>\n"
				+ "            </processControlElements>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"sign_contract\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <outputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </outputParam>\n" + "            <outputParam>\n" + "                <index>1</index>\n"
				+ "                <name>need_insurance</name>\n" + "                <type>boolean</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </outputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"reject\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"payment\" xsi:type=\"NetFactsType\">\n" + "            <inputParam>\n"
				+ "                <index>0</index>\n" + "                <name>contract</name>\n"
				+ "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <localVariable>\n" + "                <index>1</index>\n"
				+ "                <name>contact</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue/>\n" + "            </localVariable>\n"
				+ "            <localVariable>\n" + "                <index>2</index>\n"
				+ "                <name>isCash</name>\n" + "                <type>boolean</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <initialValue/>\n" + "            </localVariable>\n"
				+ "            <processControlElements>\n" + "                <inputCondition id=\"InputCondition\">\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"choose_method\"/>\n"
				+ "                    </flowsInto>\n" + "                </inputCondition>\n"
				+ "                <task id=\"choose_method\">\n" + "                    <name>choose_method</name>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"bank_guarantee\"/>\n"
				+ "                        <isDefaultFlow/>\n" + "                    </flowsInto>\n"
				+ "                    <flowsInto>\n" + "                        <nextElementRef id=\"cash\"/>\n"
				+ "                        <predicate ordering=\"0\">boolean(/payment/isCash/text())!=false</predicate>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"xor\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/payment/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <completedMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;isCash&gt;{/choose_method/isCash/text()}&lt;/isCash&gt;\"/>\n"
				+ "                            <mapsTo>isCash</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </completedMappings>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-967f6f96-e4fe-43b0-ae58-ab285b96ae66</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"choose_method\"/>\n" + "                </task>\n"
				+ "                <task id=\"bank_guarantee\">\n" + "                    <name>bank_guarantee</name>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"OutputCondition\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/payment/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-967f6f96-e4fe-43b0-ae58-ab285b96ae66</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                            <familiarParticipant taskID=\"choose_method\"/>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"bank_guarantee\"/>\n" + "                </task>\n"
				+ "                <task id=\"cash\">\n" + "                    <name>cash</name>\n"
				+ "                    <flowsInto>\n"
				+ "                        <nextElementRef id=\"OutputCondition\"/>\n"
				+ "                    </flowsInto>\n" + "                    <join code=\"xor\"/>\n"
				+ "                    <split code=\"and\"/>\n" + "                    <startingMappings>\n"
				+ "                        <mapping>\n"
				+ "                            <expression query=\"&lt;contract&gt;{/payment/contract/text()}&lt;/contract&gt;\"/>\n"
				+ "                            <mapsTo>contract</mapsTo>\n" + "                        </mapping>\n"
				+ "                    </startingMappings>\n" + "                    <resourcing>\n"
				+ "                        <offer initiator=\"system\">\n"
				+ "                            <distributionSet>\n" + "                                <initialSet>\n"
				+ "                                    <role>RO-967f6f96-e4fe-43b0-ae58-ab285b96ae66</role>\n"
				+ "                                </initialSet>\n" + "                            </distributionSet>\n"
				+ "                            <familiarParticipant taskID=\"choose_method\"/>\n"
				+ "                        </offer>\n" + "                        <allocate initiator=\"system\">\n"
				+ "                            <allocator>\n"
				+ "                                <name>RandomChoice</name>\n"
				+ "                            </allocator>\n" + "                        </allocate>\n"
				+ "                        <start initiator=\"system\"/>\n" + "                    </resourcing>\n"
				+ "                    <decomposesTo id=\"cash\"/>\n" + "                </task>\n"
				+ "                <outputCondition id=\"OutputCondition\"/>\n"
				+ "            </processControlElements>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"apply_bg\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>application_form</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"insure\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"goods_arrival\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"fill_in_bg_form\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <outputParam>\n" + "                <index>1</index>\n"
				+ "                <name>application_form</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </outputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"bank_guarantee\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"check_insurance_doc\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <outputParam>\n" + "                <index>1</index>\n"
				+ "                <name>isInsuranced</name>\n" + "                <type>insurance_status</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <defaultValue>insured</defaultValue>\n" + "            </outputParam>\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"tax\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"cash\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"choose_method\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <inputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </inputParam>\n" + "            <outputParam>\n" + "                <index>0</index>\n"
				+ "                <name>contract</name>\n" + "                <type>string</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </outputParam>\n" + "            <outputParam>\n" + "                <index>1</index>\n"
				+ "                <name>isCash</name>\n" + "                <type>boolean</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "                <defaultValue>true</defaultValue>\n" + "            </outputParam>\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"deliver_to_storage\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"wait_for_ship_order\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"urge_for_insurance\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "        <decomposition id=\"order_bg_inconsistent\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <outputParam>\n" + "                <index>0</index>\n"
				+ "                <name>bg_status</name>\n" + "                <type>bg_order_status</type>\n"
				+ "                <namespace>http://www.w3.org/2001/XMLSchema</namespace>\n"
				+ "            </outputParam>\n" + "            <externalInteraction>manual</externalInteraction>\n"
				+ "        </decomposition>\n"
				+ "        <decomposition id=\"inspectation\" xsi:type=\"WebServiceGatewayFactsType\">\n"
				+ "            <externalInteraction>manual</externalInteraction>\n" + "        </decomposition>\n"
				+ "    </specification>\n" + "    <layout>\n" + "        <locale language=\"zh\" country=\"CN\"/>\n"
				+ "        <specification id=\"hw\">\n" + "            <size w=\"95\" h=\"51\"/>\n"
				+ "            <net id=\"payment\">\n"
				+ "                <bounds x=\"0\" y=\"0\" w=\"1210\" h=\"440\"/>\n"
				+ "                <frame x=\"2\" y=\"27\" w=\"1213\" h=\"443\"/>\n"
				+ "                <viewport x=\"0\" y=\"0\" w=\"1213\" h=\"443\"/>\n"
				+ "                <vertex id=\"InputCondition\">\n" + "                    <attributes>\n"
				+ "                        <bounds x=\"36.0\" y=\"214.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                    </attributes>\n" + "                </vertex>\n"
				+ "                <vertex id=\"OutputCondition\">\n" + "                    <attributes>\n"
				+ "                        <bounds x=\"376.0\" y=\"214.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                    </attributes>\n" + "                </vertex>\n"
				+ "                <container id=\"cash\">\n" + "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"244.0\" y=\"148.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"212.0\" y=\"180.0\" w=\"96.0\" h=\"22.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"bank_guarantee\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"244.0\" y=\"280.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"203.0\" y=\"312.0\" w=\"114.0\" h=\"22.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"choose_method\">\n"
				+ "                    <vertex>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"112.0\" y=\"214.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"76.0\" y=\"248.0\" w=\"113.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                    <decorator type=\"XOR_split\">\n"
				+ "                        <position>13</position>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"143.0\" y=\"214.0\" w=\"11.0\" h=\"32.0\"/>\n"
				+ "                            <size w=\"11\" h=\"32\"/>\n" + "                        </attributes>\n"
				+ "                    </decorator>\n" + "                </container>\n"
				+ "                <flow source=\"cash\" target=\"OutputCondition\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"275.0\" y=\"163.5\"/>\n"
				+ "                            <value x=\"376.0\" y=\"229.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"InputCondition\" target=\"choose_method\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"bank_guarantee\" target=\"OutputCondition\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"275.0\" y=\"295.5\"/>\n"
				+ "                            <value x=\"376.0\" y=\"229.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"choose_method\" target=\"bank_guarantee\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"153.0\" y=\"229.5\"/>\n"
				+ "                            <value x=\"244.0\" y=\"295.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"choose_method\" target=\"cash\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"153.0\" y=\"229.5\"/>\n"
				+ "                            <value x=\"244.0\" y=\"163.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "            </net>\n" + "            <net id=\"main\">\n"
				+ "                <bounds x=\"0\" y=\"0\" w=\"1210\" h=\"440\"/>\n"
				+ "                <frame x=\"2\" y=\"27\" w=\"1213\" h=\"443\"/>\n"
				+ "                <viewport x=\"0\" y=\"0\" w=\"1213\" h=\"443\"/>\n"
				+ "                <vertex id=\"InputCondition_1\">\n" + "                    <attributes>\n"
				+ "                        <bounds x=\"24.0\" y=\"179.3\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                    </attributes>\n" + "                </vertex>\n"
				+ "                <vertex id=\"OutputCondition_1\">\n" + "                    <attributes>\n"
				+ "                        <bounds x=\"1120.0\" y=\"191.3\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                    </attributes>\n" + "                </vertex>\n"
				+ "                <container id=\"check_insurance_doc\">\n" + "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"444.0\" y=\"204.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"388.0\" y=\"236.0\" w=\"157.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                    <decorator type=\"XOR_split\">\n"
				+ "                        <position>13</position>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"475.0\" y=\"204.0\" w=\"11.0\" h=\"32.0\"/>\n"
				+ "                            <size w=\"11\" h=\"32\"/>\n" + "                        </attributes>\n"
				+ "                    </decorator>\n" + "                </container>\n"
				+ "                <container id=\"insure\">\n" + "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"532.0\" y=\"52.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"500.0\" y=\"84.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"wait_for_ship_order\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"400.0\" y=\"53.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <decorator type=\"XOR_split\">\n"
				+ "                        <position>13</position>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"431.0\" y=\"53.0\" w=\"11.0\" h=\"32.0\"/>\n"
				+ "                            <size w=\"11\" h=\"32\"/>\n" + "                        </attributes>\n"
				+ "                    </decorator>\n" + "                    <label>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"350.0\" y=\"84.0\" w=\"141.0\" h=\"22.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"tax\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"894.0\" y=\"53.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"856.0\" y=\"84.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                    <decorator type=\"OR_join\">\n"
				+ "                        <position>12</position>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"884.0\" y=\"53.0\" w=\"11.0\" h=\"32.0\"/>\n"
				+ "                            <size w=\"11\" h=\"32\"/>\n" + "                        </attributes>\n"
				+ "                    </decorator>\n" + "                </container>\n"
				+ "                <container id=\"apply_bg\">\n" + "                    <vertex>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"200.0\" y=\"180.8\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"164.0\" y=\"212.0\" w=\"105.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"urge_for_insurance\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"564.0\" y=\"272.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"512.0\" y=\"304.0\" w=\"141.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"sign_contract\">\n"
				+ "                    <vertex>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"92.0\" y=\"180.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"60.0\" y=\"212.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"reject\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/RoutingTask.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"920.0\" y=\"244.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"888.0\" y=\"276.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"inspectation\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Inspect.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"808.0\" y=\"85.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"776.0\" y=\"116.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"deliver_to_storage\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"1008.0\" y=\"152.8\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"956.0\" y=\"184.0\" w=\"137.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"order_bg_not_consistent\">\n"
				+ "                    <vertex>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"730.0\" y=\"252.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"672.0\" y=\"284.0\" w=\"161.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                    <decorator type=\"XOR_split\">\n"
				+ "                        <position>13</position>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"761.0\" y=\"252.0\" w=\"11.0\" h=\"32.0\"/>\n"
				+ "                            <size w=\"11\" h=\"32\"/>\n" + "                        </attributes>\n"
				+ "                    </decorator>\n" + "                </container>\n"
				+ "                <container id=\"apply_bg_1\">\n" + "                    <vertex>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"288.0\" y=\"133.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"256.0\" y=\"164.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"goods_arrival\">\n"
				+ "                    <vertex>\n"
				+ "                        <iconpath>/org/yawlfoundation/yawl/editor/resources/taskicons/Manual.png</iconpath>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"728.0\" y=\"45.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <decorator type=\"OR_split\">\n"
				+ "                        <position>13</position>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"759.0\" y=\"45.0\" w=\"11.0\" h=\"32.0\"/>\n"
				+ "                            <size w=\"11\" h=\"32\"/>\n" + "                        </attributes>\n"
				+ "                    </decorator>\n" + "                    <label>\n"
				+ "                        <attributes>\n"
				+ "                            <bounds x=\"700.0\" y=\"76.0\" w=\"97.0\" h=\"22.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"payment\">\n"
				+ "                    <vertex>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"808.0\" y=\"4.0\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"776.0\" y=\"36.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n" + "                <container id=\"insured\">\n"
				+ "                    <vertex>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"624.0\" y=\"191.3\" w=\"32.0\" h=\"32.0\"/>\n"
				+ "                        </attributes>\n" + "                    </vertex>\n"
				+ "                    <label>\n" + "                        <attributes>\n"
				+ "                            <bounds x=\"592.0\" y=\"224.0\" w=\"97.0\" h=\"25.0\"/>\n"
				+ "                        </attributes>\n" + "                    </label>\n"
				+ "                </container>\n"
				+ "                <flow source=\"insured\" target=\"order_bg_not_consistent\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"655.0\" y=\"206.8\"/>\n"
				+ "                            <value x=\"730.0\" y=\"267.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"reject\" target=\"OutputCondition_1\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"951.0\" y=\"259.5\"/>\n"
				+ "                            <value x=\"1120.0\" y=\"206.8\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"insure\" target=\"insured\">\n"
				+ "                    <ports in=\"13\" out=\"10\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>13</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"563.0\" y=\"67.5\"/>\n"
				+ "                            <value x=\"628.0\" y=\"112.0\"/>\n"
				+ "                            <value x=\"639.5\" y=\"191.3\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"deliver_to_storage\" target=\"OutputCondition_1\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"1039.0\" y=\"168.3\"/>\n"
				+ "                            <value x=\"1120.0\" y=\"206.8\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"check_insurance_doc\" target=\"insured\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"485.0\" y=\"219.5\"/>\n"
				+ "                            <value x=\"624.0\" y=\"206.8\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"urge_for_insurance\" target=\"insured\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"InputCondition_1\" target=\"sign_contract\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"55.0\" y=\"194.8\"/>\n"
				+ "                            <value x=\"92.0\" y=\"196.3\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"payment\" target=\"tax\">\n"
				+ "                    <ports in=\"13\" out=\"2\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"839.0\" y=\"19.5\"/>\n"
				+ "                            <value x=\"884.0\" y=\"68.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"inspectation\" target=\"tax\">\n"
				+ "                    <ports in=\"13\" out=\"2\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"839.0\" y=\"100.5\"/>\n"
				+ "                            <value x=\"884.0\" y=\"68.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"order_bg_not_consistent\" target=\"reject\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"771.0\" y=\"267.5\"/>\n"
				+ "                            <value x=\"920.0\" y=\"259.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"sign_contract\" target=\"apply_bg\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"123.0\" y=\"196.3\"/>\n"
				+ "                            <value x=\"200.0\" y=\"196.3\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"apply_bg\" target=\"apply_bg_1\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"231.0\" y=\"196.3\"/>\n"
				+ "                            <value x=\"288.0\" y=\"148.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"check_insurance_doc\" target=\"urge_for_insurance\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"485.0\" y=\"219.5\"/>\n"
				+ "                            <value x=\"564.0\" y=\"287.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"tax\" target=\"deliver_to_storage\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>12</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"925.0\" y=\"68.5\"/>\n"
				+ "                            <value x=\"956.0\" y=\"84.0\"/>\n"
				+ "                            <value x=\"968.0\" y=\"156.0\"/>\n"
				+ "                            <value x=\"1008.0\" y=\"168.3\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "                <flow source=\"goods_arrival\" target=\"payment\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"765.0\" y=\"68.5\"/>\n"
				+ "                            <value x=\"808.0\" y=\"19.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"order_bg_not_consistent\" target=\"goods_arrival\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>13</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"771.0\" y=\"267.5\"/>\n"
				+ "                            <value x=\"800.0\" y=\"240.0\"/>\n"
				+ "                            <value x=\"712.0\" y=\"176.0\"/>\n"
				+ "                            <value x=\"714.0\" y=\"68.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"apply_bg_1\" target=\"wait_for_ship_order\">\n"
				+ "                    <ports in=\"13\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>12</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"319.0\" y=\"148.5\"/>\n"
				+ "                            <value x=\"336.0\" y=\"97.0\"/>\n"
				+ "                            <value x=\"390.0\" y=\"68.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"wait_for_ship_order\" target=\"check_insurance_doc\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>12</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"441.0\" y=\"68.5\"/>\n"
				+ "                            <value x=\"464.0\" y=\"126.0\"/>\n"
				+ "                            <value x=\"432.0\" y=\"192.0\"/>\n"
				+ "                            <value x=\"444.0\" y=\"219.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"goods_arrival\" target=\"inspectation\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"765.0\" y=\"68.5\"/>\n"
				+ "                            <value x=\"808.0\" y=\"100.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n"
				+ "                <flow source=\"wait_for_ship_order\" target=\"insure\">\n"
				+ "                    <ports in=\"2\" out=\"12\"/>\n" + "                    <attributes>\n"
				+ "                        <lineStyle>11</lineStyle>\n" + "                        <points>\n"
				+ "                            <value x=\"441.0\" y=\"68.5\"/>\n"
				+ "                            <value x=\"532.0\" y=\"67.5\"/>\n"
				+ "                        </points>\n" + "                    </attributes>\n"
				+ "                </flow>\n" + "            </net>\n" + "        </specification>\n"
				+ "    </layout>\n" + "</specificationSet>\n" + "\n" + "\n";
        InterfaceA_EnvironmentBasedClient ia = new InterfaceA_EnvironmentBasedClient("http://localhost:8080/yawl/ia");
		Engine engine = engineRepo.findOne("577228d01c410020781ee567");
		// String session =
		// "868c815a-09b9-4e82-82c7-a7e62e733d2a";//ia.connect("admin", "YAWL");
		HashMap<String, Object> params = new HashMap<>();
		params.put("sessionHandle", connectionService.getSession(engine));
		params.put("specXML", sp);
		params.put("action", "getAccounts");

		String result = Requests.get("http://localhost:8080/yawl/ia/").params(params).timeout(30000).send()
				.readToText();
		System.out.println(result);
    }
}
